name: Deploy Snapshot
on:
  push:
    branches: [ 'basepatches' ]
    paths-ignore:
      - 'license/*'
      - 'readme.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'

jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v2
      - name: Deploy Version
        run: ./gradlew publishAllPublicationsToCanvasmcRepository
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}